In [ ]:
#List
aList = ["Willy",20,"Tangsel",True]
print(aList)


['Willy', 20, 'Tangsel', True]


In [ ]:
aList = ["Mahasiswa","Willy Phang Giean Restu",2022071024,"Informatika","Desain dan Analisis Algoritma","13-09-2023","Universitas Pembangunan Jaya"]
print(aList)

['Mahasiswa', 'Willy Phang Giean Restu', 2022071024, 'Informatika', 'Desain dan Analisis Algoritma', '13-09-2023', 'Universitas Pembangunan Jaya']


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[2]


'Blue'

In [ ]:
bin_alist=["Mahasiswa","Willy",2022071024]
bin_alist[2]

2021071018

In [ ]:
bin_alist=["Mahasiswa","Willy",2022071024]
bin_alist[1]

'Willy'

In [ ]:
aList[6]

'Universitas Pembangunan Jaya'

In [ ]:

aList[2:4]

[2022071024, 'Informatika']

In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
	print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
bin_alist=["Mahasiswa","Willy Phang Giean Restu",2022071024,"Informatika","Desain dan Analisis Algoritma","13-09-2023","Universitas Pembangunan Jaya"]
  for adataMahasiswa in bin_alist:
    print

IndentationError: ignored

In [ ]:
aList = ["Mahasiswa","Willy Phang Giean Restu",2022071024,"Informatika","Desain dan Analisis Algoritma","13-09-2023","Universitas Pembangunan Jaya"]
print(aList)
for dataMahasiswa in bin_alist:
  print("UPJ" , dataMahasiswa)

['Mahasiswa', 'Willy Phang Giean Restu', 2022071024, 'Informatika', 'Desain dan Analisis Algoritma', '13-09-2023', 'Universitas Pembangunan Jaya']
UPJ Mahasiswa
UPJ Willy
UPJ 2021071018


In [ ]:
import numpy as np
import datetime
tanggal = datetime.date.today ()


aList_nama = ["Willy Phang Giean Restu",  "2022071024", "Informatika", "Desain Analisis Algoritma", str(tanggal), "Universitas Pembangunan Jaya"]
for Mahasiswa in aList_nama:
    print("UPJ " + Mahasiswa) #UNTUK MENAMBAH KATA "UPJ" KE DALAM LIST YANG SUDAH DIBUAT

UPJ Willy Phang Giean Restu
UPJ 2022071024
UPJ Informatika
UPJ Desain Analisis Algoritma
UPJ 2023-09-13
UPJ Universitas Pembangunan Jaya


In [ ]:
#Nested Tuple
nested_tuple = ([100],[200,400,600],[300],[400,800])
print(nested_tuple)

([100], [200, 400, 600], [300], [400, 800])


In [ ]:
#Dictionary
bin_colors=('Red','Green','Blue','Yellow')
bin_colors[1]
'Green'
bin_colors[2:]
('Blue', 'Yellow')

('Blue', 'Yellow')

In [ ]:
#Dictionary
bin_colors ={
"manual_color": "Yellow",
"approved_color": "Green",
"refused_color": "Red"}

print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
#Dictionary
bin_colors.get("approved_color")

'Green'

In [ ]:
bin_colors['approved_color']

'Green'

In [ ]:
#Dictionary
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
green={'grass','leaves'}
print(green)

{'leaves', 'grass'}


In [2]:
yellow = {'dandelions','leaves','fire hydrant'}
red = {'rose','blood','leaves','fire hydrant'}
print(yellow|red)
print(yellow&red)

{'rose', 'dandelions', 'fire hydrant', 'leaves', 'blood'}
{'fire hydrant', 'leaves'}


In [4]:
import pandas as pd

df = pd.DataFrame([
    [1, "Informatika", 50, 30, 20],
    [2, "Sistem Informasi", 55, 30, 25],
    [3, "Teknik Sipil", 40, 30, 10]
])

df.columns = ["No", "Prodi", "Mahasiswa", "laki-laki", "Perempuan"]
df.style.hide(axis='index')


In [5]:
import numpy as np

matrix = np.array([
    [100, 200, 300],
    [700, 600, 500],
    [900, 1000, 800]
    ])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]


In [7]:
#Inisiasi Set
set_01 = {4,5,6,2}
print("set_01 = ", set_01)

#inisiasi mengubah list menjadi set
set_02 = set()
set_03 = set([2,1,4,3])

print(type(set_02))
print("set_03 = ", set_03)

print("\nmenambah")
set_01.add(576)
print(set_01)

print("\nmenghapus")
set_01.discard(6)
print(set_01)

print("\nunion")
print(set_01|set_03)

print("\nintersection")
print(set_01&set_03)

print("\ndifference")
print(set_01-set_03)

print("\nsymmetric difference")
print(set_01^set_03)

set_01 =  {2, 4, 5, 6}
<class 'set'>
set_03 =  {1, 2, 3, 4}

menambah
{576, 2, 4, 5, 6}

menghapus
{576, 2, 4, 5}

union
{576, 1, 2, 3, 4, 5}

intersection
{2, 4}

difference
{576, 5}

symmetric difference
{576, 1, 3, 5}


In [6]:
#DataFrames
import pandas as pd
df=pd.DataFrame([
                 ['1','Fares',32,True],
                 ['2','Elena',23,False],
                 ['3','Steven',40,True]])
df.columns = ['id','name','age','decision']
df


id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True